---
kind: pipeline
name: default

steps:
  - name: Run rspec
    image: ruby:2.6.5
    commands:
      - gem update bundler
      - bundle --jobs $(nproc)
      - bundle exec rspec

  - name: Bump and tag
    image: quay.io/openware/sdk-tools:1.0.0-1288533
    environment:
      BOT_NAME: Kite
      BOT_EMAIL: kite-bot@heliostech.fr
      BOT_USERNAME: kite-bot
      BRANCH_NAME: ${DRONE_BRANCH}
      REPO_NAME: ${DRONE_REPO}
      GITHUB_API_KEY:
        from_secret: kite_bot_key
    commands:
      - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile ci:prebuild
    when:
      branch:
        - master

  - name: Publish to RubyGems
    image: ruby:2.6
    environment:
      RUBYGEMS_API_KEY:
        from_secret: rubygems_api_key
    commands:
      - mkdir ~/.gem
      - |
        echo "---\n:rubygems_api_key: $RUBYGEMS_API_KEY" > ~/.gem/credentials
      - chmod 0600 ~/.gem/credentials
      - gem update bundler
      - bundle --jobs $(nproc)
      - bundle exec gem build compose-hook.gemspec
      - bundle exec gem push compose-hook-$DRONE_TAG.gem
    when:
      branch:
        - master

trigger:
  event:
    - push
