---
kind: pipeline
name: default

steps:
  - name: Run rspec
    image: ruby:2.6.5
    commands:
      - gem update bundler
      - bundle --jobs $(nproc)
      - rspec spec

  - name: Bump and tag
    image: quay.io/openware/sdk-tools:1.0.0-1288533
    environment:
      BOT_NAME: Kite
      BOT_EMAIL: kite-bot@heliostech.fr
      BOT_USERNAME: kite-bot
      BRANCH_NAME: ${DRONE_BRANCH}
      REPO_NAME: ${DRONE_REPO}
      GITHUB_API_KEY:
        from_secret: kite_bot_key
    commands:
      - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile ci:prebuild
    when:
      branch:
        - master

trigger:
  event:
    - push
